# Ejercicios NumPy

---
## Para empezar...

Antes de empezar a trabajar de verdad, tendrás que importar la librería de NumPy:

In [1]:
import numpy as np

---
## Ejercicio 1

Crea una array bidimensional, de tamaño 10x10, con valores de tipo float32 aleatorios entre 0 y 10, redondeados a 2 decimales. Luego, muestra las dimensiones, el tamaño y la forma que tiene mediante las propiedades correspondientes. Finalmente, calcula la suma de todos los valores, la media, obtén el valor máximo y el mínimo.

In [2]:
#SOLUCION 1
#array_one = np.array(np.full((10,10),[np.random.uniform(low=0, high=10)]),dtype=np.float32)
#print(array_one)
#SOLUCION 2
array_one = (np.random.rand(10,10)*10).astype(np.float32)
array_round = np.round(array_one,decimals=2)
print(array_round)
print(f'Dimensiones: {array_one.ndim}')
print(f'Tamaño: {array_one.size}')
print(f'Forma: {array_one.shape}')
print(f'Suma de total de valores: {array_round.sum()}')
print(f'La media de valores: {np.average(array_round)}')
print(f'Valor maximo: {array_one.max()}')
print(f'Valor minimo: {array_one.min()}')


[[4.22 2.29 6.24 3.5  7.4  3.18 4.23 4.41 4.9  2.04]
 [6.14 8.15 0.91 1.29 0.01 6.77 7.63 4.36 6.59 7.56]
 [0.45 0.19 2.04 8.72 0.31 6.22 8.49 8.15 2.14 0.24]
 [6.32 7.82 6.08 6.5  7.85 5.67 8.99 7.86 6.2  8.29]
 [2.3  5.19 0.73 4.9  3.88 4.03 3.98 9.29 7.26 6.44]
 [4.25 1.37 3.76 7.69 0.67 6.85 2.32 7.26 0.26 9.71]
 [6.44 7.17 7.23 4.04 6.2  5.19 9.82 2.52 7.2  9.65]
 [4.11 7.45 6.73 2.68 5.53 0.08 8.57 6.94 4.81 9.68]
 [2.91 2.28 3.76 6.75 3.83 8.47 6.4  3.01 8.44 1.71]
 [9.37 0.33 7.24 3.81 9.73 9.75 8.23 5.21 8.46 3.08]]
Dimensiones: 2
Tamaño: 100
Forma: (10, 10)
Suma de total de valores: 527.300048828125
La media de valores: 5.273000717163086
Valor maximo: 9.818349838256836
Valor minimo: 0.0107754897326231


---
## Ejercicio 2

Crea un array de una dimensión de tipo int8. En una de las posiciones pon el valor 1000. ¿Qué ocurre y porqué?

In [3]:
array_two = np.array([1,30,50,1000],dtype=np.int8)
print(array_two)

OverflowError: Python integer 1000 out of bounds for int8

A continuación ejecuta alguna solución para este problema, ¿que harías?

In [39]:
array_two = np.array([1,30,50,1000],dtype=np.int16)
print(array_two)

[   1   30   50 1000]


---
## Ejercicio 3

Crea un array con 20 valores entre los números 1 y 2. Estos valores deben estar distribuídos de manera equitativa:

In [71]:
array_three = np.linspace(1, 2, 20)
array_three = np.round(array_three, decimals=2)
print(array_three)

[1.   1.05 1.11 1.16 1.21 1.26 1.32 1.37 1.42 1.47 1.53 1.58 1.63 1.68
 1.74 1.79 1.84 1.89 1.95 2.  ]


---
## Ejercicio 4

Crea una matriz de forma 2x3 y muéstrala por pantalla. A continuación cambia su forma a una matriz 3x2. Luego obtén el resultado de multiplicar la primera por la segunda.

In [5]:
array_fourth = (np.random.rand(2,3)*10).astype(np.int32)
print(array_fourth)
array_reshape = np.reshape(array_fourth,(3,2))
print(array_fourth)
array_result = np.dot(array_fourth, array_reshape)
print(array_result)


[[0 6 4]
 [9 7 5]]
[[0 6]
 [4 9]
 [7 5]]
2


---
## Ejercicio 5

Crea un array de 6x6 con números enteros aleatorios entre 0 y 10, luego realiza las siguientes operaciones:
* Extrae la submatriz formada por las dos primeras filas y las tres primeras columnas.
* Selecciona todas las filas, pero solo las columnas desde la 2ª hasta la 4ª.
* Reemplaza todos los elementos en las tres primeras filas y tres primeras columnas con el valor 0.
* Selecciona los elementos de las dos últimas filas que son mayores a 3

In [77]:
array_five = np.random.randint(0,11,(6,6))
print(array_five)
print('*********************')
array_first_rows = array_five [:2,:3]
print(array_first_rows)
print('*********************')
array_rows = array_five [2:5]
print(array_rows)
print('*********************')
array_five [:3,:3] = 0
print(array_five)
print('*********************')
array_last_rows = array_five[4:, :]
print(array_last_rows)
array_flatten = array_last_rows.flatten()
array_max = array_flatten[array_flatten>3]
print(f'Elementos mayores a 3: {array_max}')
#num_array_max = np.max(array_max.flatten())
#print(num_array_max)


[[ 4  0 10  7  0  0]
 [ 8  6 10  7  3  9]
 [ 6  2  8  0  3  9]
 [ 4  5  8  2  8  9]
 [ 9  9  9  0  6  3]
 [ 5 10  9  5  2  0]]
*********************
[[ 4  0 10]
 [ 8  6 10]]
*********************
[[6 2 8 0 3 9]
 [4 5 8 2 8 9]
 [9 9 9 0 6 3]]
*********************
[[ 0  0  0  7  0  0]
 [ 0  0  0  7  3  9]
 [ 0  0  0  0  3  9]
 [ 4  5  8  2  8  9]
 [ 9  9  9  0  6  3]
 [ 5 10  9  5  2  0]]
*********************
[[ 9  9  9  0  6  3]
 [ 5 10  9  5  2  0]]
Elementos mayores a 3: [ 9  9  9  6  5 10  9  5]


---
## Ejercicio 6

Crea un array de tamaño 8x8 con valores enteros aleatorios entre 1 y 100, realiza las siguientes operaciones utilizando máscaras booleanas:

* Crea una máscara que identifique los elementos mayores a 50 y reemplázalos por el valor 100.
* Crea una máscara que identifique los elementos menores o iguales a 20 y reemplázalos por el valor -1.
* Cuenta cuántos elementos del array son pares y cuántos son impares.
* Crea una nueva matriz donde se reemplacen los elementos pares por su mitad y los impares por su doble.

In [108]:
array_six = np.random.randint(1,100,(8,8))
#print(array_six)
#print('*********************')
array_six[array_six>50] = 100
#print(array_six)
#print('*********************')
array_six[array_six<=20] = -1
#print(array_six)
#print('*********************')
num_par = 0
num_impar = 0
for row in array_six:
    for num in row:
        if num % 2 == 0:
            num_par = num_par +1
        else:
            num_impar = num_impar +1

print(f"Cantidad num pares: {num_par}")
print(f"Cantidad num impares {num_impar}")

array_new = np.random.randint(1,100,(8,8))
print(array_new)
for row in range(len(array_new)):
    for col in range(len(array_new[row])):
        if array_new[row][col] % 2 == 0:
            array_new[row][col] = array_new[row][col] / 2
        else:
            array_new[row][col] = array_new[row][col] * 2
print("Array resultado:")
print(array_new)

Cantidad num pares: 36
Cantidad num impares 28
[[30 42 20 42 84 34 50 44]
 [50 70 87 15 83 83  6  9]
 [63 60 41 31 49 48 48 73]
 [95 51 27 22 20 49 98  5]
 [70 83 12 75 21 36 53 70]
 [28 54  6 29 52 98 97 79]
 [21 53 16 97  3 86 85 73]
 [11 95 31 30 46 18 33 30]]
Array resultado:
[[ 15  21  10  21  42  17  25  22]
 [ 25  35 174  30 166 166   3  18]
 [126  30  82  62  98  24  24 146]
 [190 102  54  11  10  98  49  10]
 [ 35 166   6 150  42  18 106  35]
 [ 14  27   3  58  26  49 194 158]
 [ 42 106   8 194   6  43 170 146]
 [ 22 190  62  15  23   9  66  15]]


---
## Ejercicio 7

Sin utilizar las funciones predefinidas std ni mean de NumPy, programa dichas funcionalidades mediante 2 funciones diferentes. A esas funciones le pasarás como parámetro un array y devolverán el valor calculado. Haz un prueba con un array sencillo y muestra en pantalla los resultados. El cálculo de la media es sencillo, pero para la desviación estándar tendrás que investigar un poco.

In [7]:
def array_media (array_media = []):
    array_np = np.array(array_media)
    media = array_np.sum() / len(array_np)
    print(media)
    return media
array_example = []
array_media(array_example)

4.25


np.float64(4.25)

---
## Ejercicio 8

Dada una matriz, del tamaño que quieras, y con valores aleatorios entre 0 y 100; normaliza cada columna de la matriz utilizando la fórmula de normalización:

![image.png](attachment:image.png)

donde:
* X es una columna de la matriz,
* min(𝑋) es el valor mínimo de la columna,
* max(𝑋) es el valor máximo de la columna.